#makefile for raspberry_pi_4b, 32bit, Blinker
# Erik Bakker, 7-2025
# select pi version: raspberry_zero_1w, raspberry_zero_2w, raspberry_pi_4b
PIVERSION = raspberry_pi_4b
ARMGNU ?= arm-none-eabi-
OUTPUT = kernel.img
LINKER_SCRIPT = linker.ld
BUILD_DIR = build
SRC_DIR = src
COPY_DIR = SD_card
COMMON_MAKEFILE := ../../Makefile.common

include $(COMMON_MAKEFILE)
